<?xml version="1.0" encoding="UTF-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Authors>authors</Authors>
    
    <TargetFramework>net48</TargetFramework>
    
    <OutDir>..\Assemblies\</OutDir> 
    
    <RootNamespace>Crewmate</RootNamespace>
    <AssemblyName>Crewmate</AssemblyName>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref">
      <Version>1.6.4566</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>

    <PackageReference Include="Krafs.Publicizer">
      <Version>2.3.*</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Lib.Harmony">
      <Version>2.4.1</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>